### ISSUE TITLE
Add TcNo-Acc-Switcher to the Winget/Window's Store Repository

### ISSUE THREAD

**Issue by Void48** [TCNOco/TcNo-Acc-Switcher#120]

**Comment by TcNobo** [comment]
I've got everything prepared for the Windows Store... but I'm getting this. I can't build the MSIX package for some reason :/ 
![image](https://user-images.githubusercontent.com/10319195/150865009-97cad401-3c7c-4c2c-95f6-743b96000754.png)

**Comment by jhofer** [comment]
I Did some googling 

Check this out

https://www.meziantou.net/deploying-a-dotnet-desktop-application-using-msix.htm

`<RuntimeIdentifiers>win-x86;win-x64</RuntimeIdentifiers>`

**Comment by TCNOco** [comment]
Thanks to @Eddga this is in the winget repository. Just need to work on how it updates :) #355
