### ISSUE TITLE
(Steam) Asking for password everytime for one of my account

### ISSUE THREAD

**Issue by thu2468** [TCNOco/TcNo-Acc-Switcher#196]
So i done what the wiki said cleared everything in the cleaning setting in the app.

So i got two account working. it has steam guard enable. the third account just will keep signing out asking for a code everytime.

**Comment by TcNobo** [comment]
Unfortunately, whether Steam accounts say authenticated or is completely up to Steam. The account switcher just swaps out the "last logged in username", and Steam handles the rest.

Try logging into the problematic account, removing it from the TcNo Account Switcher - And then use the `Log Out` button in Steam. Idk if a restart would help, but now's a good time. Then log back into the account, and it should hopefully be working properly. The Wiki link below has some more troubleshooting steps.

Check the Wiki for [Steam - I need to enter a password every time I switch](https://github.com/TcNobo/TcNo-Acc-Switcher/wiki/FAQ---More-Info#i-need-to-enter-a-password-every-time-i-switch---steam). This should help.

**Comment by TcNobo** [comment]
There is an issue affecting few users where the files aren't being edited properly when switching, specifically `loginusers.vdf`. If this is happening to you, you should see a popup error notification when switching accounts - If you haven't already found a solution https://github.com/TcNobo/TcNo-Acc-Switcher/releases/tag/2022-03-29_00

**Comment by thu2468** [comment]
i did both thing still doesnt save password

**Comment by thu2468** [comment]
how do you fully wipe the cache where steam save login? b.c i think it not getting fully wipe b.c when i change password it breaks and doesnt let me save login

**Comment by TcNobo** [comment]
Steam completely handles logins, the logincache in the account switcher is just for icons, sorting and other things.
To clear Steam logins open the `TcNo Account Switcher` > `Steam` > `Settings` > At the bottom click `Advanced cleaning...`.
After clicking "I understand" and "Kill Steam process" steam will close.
Then you can click `loginusers.vdf`, `ssfn*`, `config.vdf`, and all the `HKCU` buttons to completely clear cached logins for Steam.

After clicking those buttons, you will need to log into all your Steam accounts again.

**Comment by thu2468** [comment]
I did that again and that doesnt work.

**Comment by thu2468** [comment]
i was able to get it work when i remove Steam guard then changing password. cleared everything in advanced cleaning. Login again without steam guard and it works. And then i added steam guard back. So there something else remembering some auth

**Comment by TcNobo** [comment]
Do other accounts work? Do other accounts work with Steam auth?
I've been able to swap accounts with and without 2-factor :/ (Mobile 2-factor. Every account has steam guard with email set up)

**Comment by thu2468** [comment]
yes the other account works with steam guard and with email

**Comment by TcNobo** [comment]
And then it works...? Super odd.
I'm not sure why but I'm glad you got it working. I'll add similar steps to the wiki

**Comment by thu2468** [comment]
is there maybe another place where steam is holding cache of login and trying to use that or backup cache

**Comment by TcNobo** [comment]
Not that I'm aware of unfortunately.

**Comment by thu2468** [comment]
Oh ok thats unforunate. i think something weird is happening b.c it works on someone else computer but just not on mine

**Comment by thu2468** [comment]
So i think something is still holding the old password

**Comment by 9xKiritox6** [comment]
I tend to have the same Issue, but I fixed it by changing the other account into different Profile Name... In my side the problem occurs when both accounts have the same Profile Name

![image](https://user-images.githubusercontent.com/81343761/166857735-bd49a4ca-3692-488f-a6e3-2e8c5ce923fd.png)
Now, I change my 2nd Acc with different ASCII of Quotation Signs so that it may still look similar Profile Name, but still different as a value due to it's different ASCII.

**Comment by TCNOco** [comment]
It's been a while since this issue's creation, so I'll close as likely resolved.
Please try the [latest release](https://github.com/TCNOco/TcNo-Acc-Switcher/releases/latest) - Ready for download!
If there are any issues, let me know on Discord, or through a new issue.
