### ISSUE TITLE
tcno keeps crashing 

### ISSUE THREAD

**Issue by ShowravZ** [TCNOco/TcNo-Acc-Switcher#210]
![image](https://user-images.githubusercontent.com/96135426/167249666-f51a1b56-6c9d-46c2-b557-0e3802e4740d.png)

TCNO is crashing whenever I try to open steam section. Also, when I try to use it from system tray, it does not let me login in another account. 

![image](https://user-images.githubusercontent.com/96135426/167249849-a01794ee-a6d3-4a34-9fa8-3f2b45689901.png)

- I tried reinstalling
- clearing steam caches
- updating

Discord, riot games etc are working just fine. Please check

**Comment by ShowravZ** [comment]
Fixed... Just had to delete app data from 

C: > Users > "Your User Name" > AppData > Roaming

**Comment by TcNobo** [comment]
It's having an issue getting an icon from a shortcut for a game, I assume?
Go to `%AppData%\TcNo Account Switcher\LoginCache\<platform>\Shortcuts\` (where `<platform>` is the one you're having issues with).
Then delete any shortcuts that seem broken, or clear them entirely.

I will have a further look into this tomorrow. Let me know if the above fix worked for you.

**Comment by ShowravZ** [comment]
I tried the above didn't work for me.. 

It occurs when TCNO steam switcher is freshly opened or while trying from quick switch option in system tray. Sometimes, TCNO auto closes after showing the error message

**Comment by exelysion** [comment]
I'm having similar issue here
<img width="1373" alt="Screenshot 2022-06-26 211309" src="https://user-images.githubusercontent.com/108220355/175811472-c6a74e9e-ae71-4b37-9c45-dd1155f1902d.png">

**Comment by TcNobo** [comment]
> I'm having similar issue here <img alt="Screenshot 2022-06-26 211309" width="1373" src="https://user-images.githubusercontent.com/108220355/175811472-c6a74e9e-ae71-4b37-9c45-dd1155f1902d.png">

This error in particular is caused by your computer not being able to communicate with https://tcno.co/ to check for updates. You shouldn't see an error like this for this issue. I will have to double-check to see if it is ignored (as it should be)
