### ISSUE TITLE
i would like some help! (help needed)

### ISSUE THREAD

**Issue by dr1verz** [TCNOco/TcNo-Acc-Switcher#216]
my problem is microsoft Microsoft ASP.NET Core 6.0.4 Runtime does not download with the tcno account switcher runtime installer and i tryed downloading it manuly but it did not work.

**Comment by TcNobo** [comment]
I am unfortunately unable to recreate this, however, if you're not able to manually download the .NET 6.0.4 runtime from Microsoft, then unfortunately it likely has to do with them, or your connection to Microsoft servers.

.NET can be downloaded from: https://dotnet.microsoft.com/en-us/download/dotnet/6.0
