### ISSUE TITLE
Epic games doesnt work

### ISSUE THREAD

**Issue by AdnanZXgamer** [TCNOco/TcNo-Acc-Switcher#223]
I click add new and I sign in but the account doesn't pop up

**Comment by TcNobo** [comment]
You need to click Save, to save the account you just logged into. The Add New button only clears the login, while keeping the previous one 'frozen' to return to/swap to in the future. Logging out normally doesn't keep the login 'frozen' like this software does.

**Comment by AdnanZXgamer** [comment]
but if I save i can only freeze one account, if i want to switch, ill have to login to that account manually

**Comment by TcNobo** [comment]
No, you can have as many accounts as you want saved and 'frozen'. The whole point is you sign in, save the account, add a new account, save it - as many times as you want and you can switch between them. No password, no 2-factor.

You should be able to switch between multiple accounts.

**Comment by TCNOco** [comment]
This shuold be further improved with the [latest release](https://github.com/TCNOco/TcNo-Acc-Switcher/releases/latest) - Ready for download!
Closing this issue as resolved. Thanks for the input.
If there are any issues, let me know on Discord, or through a new issue.
