### ISSUE TITLE
Setting to hide date displayed in account view

### ISSUE THREAD

**Issue by JohannesMP** [TCNOco/TcNo-Acc-Switcher#235]
![image](https://user-images.githubusercontent.com/662874/178168246-88018e96-0a4a-4ce1-8699-1e6890b94ae9.png)

I am using the launcher primarily for Steam and I'd like to be able to hide the date that is displayed under the account in the launcher by default. I have no need for it, and I would prefer a simpler look.

As best as I can tell there is currently no option to hide this information exposed in the Settings.

**Comment by TcNobo** [comment]
![image](https://user-images.githubusercontent.com/10319195/178263273-6ce7401a-c70c-4470-8430-8db2f2dbf866.png)
This change was added and will come with the upcoming update in the next few days.
