### ISSUE TITLE
Accessibility: UI scale option

### ISSUE THREAD

**Issue by JohannesMP** [TCNOco/TcNo-Acc-Switcher#236]
It would be useful if the settings exposed a UI scale option.

I am aware that I can use `Ctrl`+`=` and `Ctrl`+`-` to adjust the overall scaling of the launcher's UI, but this setting does not appear to persist. 

For example, if I use `Ctrl`+`=` to increase the UI scale, open the settings UI, and then go back to the Account view, the changes to the UI scaling will have reset to default.

-----

I am aware that you can edit the CSS of a given theme to modify the font. 

This is great for specific theme-specific changes, but I'd like to argue that a global UI scaling option would be worthwhile, especially for users with impaired vision or whose high-resolution display makes the UI hard to see.

Ideally there would just be a simple slider/input box in the 'Theme' section of the settings UI, just like what you'd see in your standard browser like Chrome
![image](https://user-images.githubusercontent.com/662874/178169022-e6f9495f-2ffb-4806-b9f5-453ca895491f.png)

<br />

A potential compromise would be to just make the current font scaling changes that are applied when using `Ctrl`+`=` and `Ctrl`+`-` persist.

Ideally both should be possible (adjusting the multiplier in settings, and using hotkeys with a value that persists).

**Comment by TcNobo** [comment]
Currently, I think the `Ctrl` + `+`/`-` method is the best. It scales everything well, and if you make the window larger it's even easier to interact with. I'll look into ways of making this persist.

Changing the font-size throws everything out of whack
![image](https://user-images.githubusercontent.com/10319195/178172523-6cd22fdd-6ec3-4c92-9c50-7437165fa909.png)
