### ISSUE TITLE
Cannot restore the vcpkg nuget

### ISSUE THREAD

**Issue by XECTRA-RAW** [TCNOco/TcNo-Acc-Switcher#253]
Please help me with installing this issue as I've tried but not working!

**Comment by TcNobo** [comment]
I have never heard of this error. Are you building the project from source?

**Comment by XECTRA-RAW** [comment]
Yes! The nuget package in the source won't restore says it missing from sdk folder

**Comment by XECTRA-RAW** [comment]
I have it installed but still saying it's missing!

**Comment by TcNobo** [comment]
You will need to relink it with the C++ project. I'm looking for the command, but I don't remember it. 
There is `vcpkg integrate`, but there's a command to integrate with project files as well as far as I remember

**Comment by TcNobo** [comment]
In [TcNo-Acc-Switcher\Installer\Installer.vcxproj](https://github.com/TcNobo/TcNo-Acc-Switcher/blob/master/Installer/Installer.vcxproj), there are the following that you can change. I'm not sure how to go about improving this for general use:

The lines with Link and vcpkg paths:
[Ln 88](https://github.com/TcNobo/TcNo-Acc-Switcher/blob/master/Installer/Installer.vcxproj#L88)
[Ln 133](https://github.com/TcNobo/TcNo-Acc-Switcher/blob/master/Installer/Installer.vcxproj#L113)

Both being paths to the static libcurl library.
Built with `x64-windows-static` as far as I remember.

I don't think these need to be changed at all.
[Ln 3](https://github.com/TcNobo/TcNo-Acc-Switcher/blob/master/Installer/Installer.vcxproj#3)
[Ln 137-139](https://github.com/TcNobo/TcNo-Acc-Switcher/blob/master/Installer/Installer.vcxproj#L137-L139)
[Ln 144-145](https://github.com/TcNobo/TcNo-Acc-Switcher/blob/master/Installer/Installer.vcxproj#L144-L145)

There must be an easier way.

**Comment by XECTRA-RAW** [comment]
Would you be able to add me on discord and send the folder over then I can just drag to my dev folder please! As i can't of installed it completely as I don't have the installed folder in my vcpkg

**Comment by TcNobo** [comment]
Unfortunately not, but the following command will build libcurl for you to include:
`./vcpkg install curl:x64-windows-static`

I would then say just edit the project file to point as follows:
```
C:\dev\vcpkg\installed\x64-windows-static\debug\lib\libcurl-d.lib
==> <where vcpkg is>\installed\x64-windows-static\debug\lib\libcurl-d.lib

C:\dev\vcpkg\installed\x64-windows-static\lib\libcurl.lib
==> <where vcpkg is>\installed\x64-windows-static\lib\libcurl.lib
```

**Comment by XECTRA-RAW** [comment]
What vcpkg package is used in the source?

**Comment by TcNobo** [comment]
https://vcpkg.io/en/index.html

As far as I remember, you only need curl to be compiled. This is for building the installer. Nothing else requires this package as far as I understand. You can probably build and run the project without ever needing to compile the installer.
