### ISSUE TITLE
Riot games asks for a password every switch

### ISSUE THREAD

**Issue by Restland** [TCNOco/TcNo-Acc-Switcher#256]
I do all the steps including the stay signed in but every time I change account it ask for username+password.. Happens only on the 2nd account that I add

**Comment by objetovazio** [comment]
I've been using it for a while and found out that just that you have to check to remember the logged account. Then, when discconecting from the game, just leave. Do not Desconect and Leave. Keep your sesssion and always open thru the TcNo.

**Comment by TCNOco** [comment]
Fixed with the [latest release](https://github.com/TCNOco/TcNo-Acc-Switcher/releases/latest) - Ready for download!
Closing this issue as resolved. Thanks for the input.
If there are any issues, let me know on Discord, or through a new issue.
