### ISSUE TITLE
[Suggestion] | PIN Code for the Programm

### ISSUE THREAD

**Issue by vxnsin** [TCNOco/TcNo-Acc-Switcher#265]
A PIN Code for the Programm every time you open the Programm you need a PIN Code or if anyone want to switch a account
because its to eaasy to log-in into a Account with the Programm without use a Password

**Comment by glappa** [comment]
yea i would like this feature too, because when your pc gets hacked someone can open all of your accounts and cheat for example on them, the pin could mitigate this Problem

**Comment by TCNOco** [comment]
Forgot to close this when this feature was added with d98569c0bcab3732f93945da2e17e6f1032da816, 2023-07-05
