### ISSUE TITLE
[suggestion] Adding a cli

### ISSUE THREAD

**Issue by Majoramari** [TCNOco/TcNo-Acc-Switcher#269]
Hello as far as I know can't use the account switcher from the terminal I hope to see something like this 
Why? Because it will allow you to make custom commands to start a specific game on the specific account without using the GUI that I hate to you use (I love the terminal)

I'm willing to contribute but I don't know C# or Windows API if you're willing to share the stack used in this project and what I need to know I could help with it

**Comment by Avery-Rose** [comment]
I think you're able to use `tcno:\\` protocol, but I have no clue how to use it or what it's capabilities are
![image](https://user-images.githubusercontent.com/92644634/204620334-f7e6b531-c953-4468-9aee-2857b97e79d6.png)
