### ISSUE TITLE
Can't write into the registry

### ISSUE THREAD

**Issue by pjean** [TCNOco/TcNo-Acc-Switcher#272]
**Describe the bug**
Each time, I launch the app, it asks me to enter admin password and when I try to save/update a new account  I get an error saying that the can't write into the registry. I tried to reinstall the app but without success. It's like a part of the app has been installled under admin space.

**To Reproduce**
Don't really know

**Expected behavior**
I would like to be able to use the app without problem.

**Screenshots**
![Error](https://user-images.githubusercontent.com/787461/204141372-6bd7cec0-d36e-495e-a953-6396dfb51563.png)

**Desktop (please complete the following information):**
 - OS: Win 11

**Additional context**
We have an admin user and a simple user configured on the computer. The problem occurs under simple user account.

**Comment by TcNobo** [comment]
The app requires access to `HKEY Current User\\Software\\Epic Games\\Unreal Engine\\Identifiers`, as it reads the `AccountId` - to know which account is currently logged in.
It will then swap this out with another account on switch.

This sounds like a limitation added by policies or third-party software on your computer. There isn't access where there should be. As far as I remember, you should be able to access these, even without admin permissions.

Have you tried running the account switcher as Admin? I know you're prompted for a password, but do so explicitly with Right-Click > Run as Administrator.

**Comment by pjean** [comment]
Sorry for the response delay, even if run the app as Admin I get the same error.
