### ISSUE TITLE
--help not working

### ISSUE THREAD

**Issue by wonson** [TCNOco/TcNo-Acc-Switcher#279]
TcNo-Acc-Switcher.exe --help
(instructed by wiki) is not working on my command prompt.
There is just a flash of a ghost window in about the size of the normal switcher window.

Environment:
Win11 64bit
Non-admin account with both normal command prompt and command prompt with "run as administrator" 

Update:
Tc-Acc-Switcher_main.exe --help 
works

Update2:
But +s:username doesn't work for non admin account anyway. Even I've entered the admin password which ui doesn't need to.

**Comment by TCNOco** [comment]
Closing this issue as stale. A lot of development has happened since this issue's creation.
Please download the [latest release](https://github.com/TCNOco/TcNo-Acc-Switcher/releases/latest) - and let me know if this still happens. It shouldn't be - hopefully.
