### ISSUE TITLE
[Suggestion] PIN on Programm opening

### ISSUE THREAD

**Issue by glappa** [TCNOco/TcNo-Acc-Switcher#283]
A PIN Code for the Programm every time you open the Programm you need a PIN Code or if anyone want to switch a account
because its to eaasy to log-in into a Account with the Programm without use a Password

**Comment by TCNOco** [comment]
Not too sure when this was added,  but the feature is present now. You can set a password via the TcNo Account Switcher's settings.

See the [latest release](https://github.com/TCNOco/TcNo-Acc-Switcher/releases/latest) - Ready for download!
Closing this issue as resolved. Thanks for the input.
If there are any issues, let me know on Discord, or through a new issue.
