### ISSUE TITLE
interface ?

### ISSUE THREAD

**Issue by stickerx** [TCNOco/TcNo-Acc-Switcher#292]
Software interface does not appear

![2023-02-03_223603](https://user-images.githubusercontent.com/41187653/216716492-2c6b2cfe-979d-4d2a-8f85-563b59d6a899.jpg)

![2023-02-03_224510](https://user-images.githubusercontent.com/41187653/216716786-1c39c436-d17c-41b7-a1a5-1c0d4a387996.jpg)

 - OS: [e.g. Win 7 Ultimat]

**Additional context**
thank you advance

**Comment by TCNOco** [comment]
Microsoft WebView2 is incompatible with Windows 7.
> For those still struggling with this: A fix is here - or well... I've implemented the suggested workaround. You can (in the next update coming a day or 2 from now) open `%AppData%\TcNo Account Switcher\WindowSettings.json` and change `"AllowTransparency": true,` to `"AllowTransparency": false,` to disable transparency
> 
> I would have implemented a tickbox... But well... If you can't see the window, you won't be ticking anything.

https://github.com/TCNOco/TcNo-Acc-Switcher/issues/183#issuecomment-1179612242
