### ISSUE TITLE
[Suggestion] GOG Support

### ISSUE THREAD

**Issue by Alyng0** [TCNOco/TcNo-Acc-Switcher#293]
GOG support pls

**Comment by Turtle-Boi** [comment]
bump

**Comment by TCNOco** [comment]
This is coming in the next update. https://github.com/TCNOco/TcNo-Acc-Switcher/commit/3ae03096492bb678df556804aefe60c4c2d07f48

**Comment by TCNOco** [comment]
Added with the [latest release](https://github.com/TCNOco/TcNo-Acc-Switcher/releases/latest) - Ready for download!
Closing this issue as resolved. Thanks for the input.
If there are any issues, let me know on Discord, or through a new issue.
