### ISSUE TITLE
EA app asks for a login and password every switch

### ISSUE THREAD

**Issue by kek-dev** [TCNOco/TcNo-Acc-Switcher#295]
Despite trying the solution suggested in the FAQ, the EA app is still requiring to enter login and password every time I switch the account. This issue is occurring on Windows 21H1.

**Comment by TCNOco** [comment]
Fixed with the [latest release](https://github.com/TCNOco/TcNo-Acc-Switcher/releases/latest) - Ready for download!
Closing this issue as resolved. Thanks for the input.
If there are any issues, let me know on Discord, or through a new issue.
