### ISSUE TITLE
firsit run installer does not install .NET framwork

### ISSUE THREAD

**Issue by LuBox2K** [TCNOco/TcNo-Acc-Switcher#298]
**firsit run installer does not install .NET framwork**

Basically whenever I run the setup, the first_run_installer.exe, after I going through the part in the cmd window, it extits with the message:
"To run this application, zou must install mmissing frameworks for .NET.

Would you like to download?
>Yes          >No"
pressing yes does nothing.
same behaviour when running the setup.exe and the _First_Run_Installer by itself.
maybe it should be noted that the cli install is skipped after the first time, since it presumably correctly installed the stuff its looking for, thus displaying said error message instantly. 
(maybe its even my windows installl refusing to do install the frameworks - I wouldn't know.)

**To Reproduce**
not sure what to put here..
I run win10 Pro ver. 10.0.19044 Build 19044

**Expected behavior**
installing the necessary .NET frameworks

**Screenshots**
![image](https://user-images.githubusercontent.com/74805856/220245674-e621bf55-9698-4659-b6a9-f200d182458c.png)

**Comment by LuBox2K** [comment]
okay, so I installed the frameworks manually - and it works now. not sure if you want to keep this issue open - But if you dont: might I suggest adding a link to said error message leading the user to the instructions for manual install ?

Adding something like: ".NET frameworks missing - manual install: https://github.com/TCNOco/TcNo-Acc-Switcher/wiki"

**Comment by TCNOco** [comment]
I'm not too sure how things were set up with downloads at the time of this issue, but this info is visible on the download page for each release, as well as the wiki mentioned, and the Readme landing page for this project.
Thank you for your input.

The first run installer was created/improved, as well as a C# wrapper that should not require any .net anything to work -- and should handle downloading and installing the required runtimes if they are missing.
