### ISSUE TITLE
Fail to use Riot Game Switcher

### ISSUE THREAD

**Issue by Folkfive** [TCNOco/TcNo-Acc-Switcher#300]
Hello, I try the software and meet some problems. I want to use Steam and Riot Games switch. It works when I use steam platform. But when I try Riot Games platform. It show 'An error has occurred. This application may no longer respond until reloaded'. And I try to get the error information as following:
![image](https://user-images.githubusercontent.com/22257912/221350329-7c49dd52-2648-44b7-86d1-019f9faa1fcb.png)

**Comment by TCNOco** [comment]
Fixed with the [latest release](https://github.com/TCNOco/TcNo-Acc-Switcher/releases/latest) - Ready for download!
Closing this issue as resolved. Thanks for the input.
If there are any issues, let me know on Discord, or through a new issue.
