### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by hesham-27** [TCNOco/TcNo-Acc-Switcher#302]
I don't know how to solve this problem

![1](https://user-images.githubusercontent.com/127259415/223573449-92a656e1-58c5-4944-9a41-655e52ccb9b7.png)

**Comment by TCNOco** [comment]
Navigate using the `C:\` and `D:\` text to find where Epic Games is installed, so the account switcher can interact with it.

For example: `C:\Program Files (x86)\Epic Games\Launcher\Portal\Binaries\Win32`
