### ISSUE TITLE
Doesnt switch accounts

### ISSUE THREAD

**Issue by Elay2306** [TCNOco/TcNo-Acc-Switcher#309]
I dont know if this is a windows 11 issue or driver issue or whatever, on my old pc with win 10 it worked all fine... now on my new win 11 pc it can open steam if its closed but it doesnt kill the process, it just restarts the account switcher. Yes i can use the close steam option or combined but i hate the UAC thingy so the only thing from the 3 options is kill the process but that like i said doesnt works :(

and yes ofc i reinstalled the whole thing

**Comment by TCNOco** [comment]
New update's released.
Please update and let me know if you're still getting this issue as well as what games/platforms you're getting this issue for

**Comment by TheSuspect2306** [comment]
so its fixed now, i can use it without the need of admin rights, thanks ! and i used steam
