### ISSUE TITLE
(X platform) asks for a password every switch

### ISSUE THREAD

**Issue by FoxhoundDutchNL** [TCNOco/TcNo-Acc-Switcher#310]
So I bought ofline account dead island 2 , when I go ofline the overlay is constantly spamming me to login the game you can play but can’t stay ofline ☹

Please help

I think that people like you makes guides so easy to understand should be king really positive energy you give me for this kind of stuff thank you

Ps.

Just upgrade but now I have no money and whit shared account and your app I enjoy the games still 😃 thnks

**Comment by FoxhoundDutchNL** [comment]
game boots but then epic store spams me with login if i press close 1 sec and again

**Comment by TCNOco** [comment]
Update to the latest TcNo Account Switcher version: https://github.com/TCNOco/TcNo-Acc-Switcher/releases/tag/2023-06-26_00

Let me know if this issue persists.

**Comment by FoxhoundDutchNL** [comment]
i needed, the disconnect my network adapter , everytime for epic store , not like steam like you are setting it in ofline mode and done, .. epicstore needs to be no internet :)
