### ISSUE TITLE
I can't add another account Battle.net

### ISSUE THREAD

**Issue by narisui** [TCNOco/TcNo-Acc-Switcher#311]
I've added 6 BattleNet accounts, but I can't add 1 more.In the settings.I have the necessary components of the working environment installed.And in the settings of the program there is a badge to remember more than 50 accounts.I also tried to install an earlier version of the program, it didn't help.How to solve the problem?

**Comment by aimslut** [comment]
the Battle.net.config file has a limit of how many usernames can be saved at once sadly.
you can overwrite it manually, but everytime you log into an account, one will be removed.

a way around it is to overwrite the file with one containing all your accounts before the TcNo account switcher starts, but can get annoying to do it manually every reboot, so I ended up making a simple powershell script to replace the files at boot.
hopefully @TCNOco can add loading emails from a secondary file to log into as many as you want without having to make a workaround as an end user.

**Comment by narisui** [comment]
> the Battle.net.config file has a limit of how many usernames can be saved at once sadly. you can overwrite it manually, but everytime you log into an account, one will be removed.
> 
> a way around it is to overwrite the file with one containing all your accounts before the TcNo account switcher starts, but can get annoying to do it manually every reboot, so I ended up making a simple powershell script to replace the files at boot. hopefully @TCNOco can add loading emails from a secondary file to log into as many as you want without having to make a workaround as an end user.

You made a script and where is it?and how to use it?

**Comment by aimslut** [comment]
Make a backup of your `Battle.net.config` file located in %appdata%/Battle.net/
Place it wherever you want, and add all the accounts you want to log into after it says `SavedAccountNames`
Make a .ps1 file with this in, and replace the locations accordingly
`ROBOCOPY C;\BackupFolder C:\BnetAppDataFolder  Battle.net.config /COPYALL `
Set that to run at startup before you launch TcNo Account Switcher

**Comment by narisui** [comment]
> Make a backup of your `Battle.net.config` file located in %appdata%/Battle.net/ Place it wherever you want, and add all the accounts you want to log into after it says `SavedAccountNames` Make a .ps1 file with this in, and replace the locations accordingly `ROBOCOPY C;\BackupFolder C:\BnetAppDataFolder Battle.net.config /COPYALL ` Set that to run at startup before you launch TcNo Account Switcher

I did both, but it doesn't work.I have the inscription "could not find the file Battle.net.config". How to solve the problem?

**Comment by aimslut** [comment]
> I did both, but it doesn't work.I have the inscription "could not find the file Battle.net.config". How to solve the problem?
Did you change the locations of the folders to where your files are located?

**Comment by narisui** [comment]
I added to the file Battle.net.config all the accounts that I want using the editor.Replaced "config" with "ps1" as you wrote. The location of the file remains the same, in the folder C:\BnetAppDataFolder .But now Ticno doesn't read this 'ps1' file.How to fix the problem?I will be grateful.

**Comment by TCNOco** [comment]
Oh, wow, I realise I never pushed the update that had this and a lot of other work.
Testing, I can happily add 7+ accounts, but I realise this isn't the public version 👀 
Working on pushing this as an update asap

**Comment by TCNOco** [comment]
Sweet, the update is live. You will need to manually save your accounts in the account switcher and re-add accounts since the last update... But you're able to add as many as you like now!

Update to the latest TcNo Account Switcher version: https://github.com/TCNOco/TcNo-Acc-Switcher/releases/tag/2023-06-26_00

Let me know if this fixes the issue for you.

**Comment by narisui** [comment]
It works!It's cool!Could you add binds to the keys?
