### ISSUE TITLE
[SUGGESTION] GOG Support

### ISSUE THREAD

**Issue by Turtle-Boi** [TCNOco/TcNo-Acc-Switcher#312]
My friend has a GOG account with a ton of games, but from time to time I want to play my own games, and I have my own GOG account with my steam/epic link and it's one big gaming hud, but then I have to ask him to check his email for a verification code again and it turns into a whole thing. I would love just plain basic GOG support.

**Comment by dlartigu** [comment]
That will be a great add !

**Comment by TCNOco** [comment]
This is coming in the next update. https://github.com/TCNOco/TcNo-Acc-Switcher/commit/3ae03096492bb678df556804aefe60c4c2d07f48
