### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by Infisrael** [TCNOco/TcNo-Acc-Switcher#313]
![image](https://github.com/TCNOco/TcNo-Acc-Switcher/assets/73630497/fc668cd0-c789-406a-9a8e-6394aa9ff6d4)

The Account switcher opens, shows this error and after 3 seconds closes itself instantly.

**Comment by TCNOco** [comment]
This should be handled, and shouldn't come up on launch... I'm busy working on a release and will comment here again once it's out. Update and let me know if it still happens (when it's out).

**Comment by TCNOco** [comment]
Update to the latest TcNo Account Switcher version: https://github.com/TCNOco/TcNo-Acc-Switcher/releases/tag/2023-06-26_00

Let me know if this fixes the issue for you.
