### ISSUE TITLE
runas.exe takes so much time before actually do something

### ISSUE THREAD

**Issue by AcTiViSioN911** [TCNOco/TcNo-Acc-Switcher#315]
**Describe the bug**
When I double click on my steam account, a new window "runas.exe" opens, and it takes like 15 seconds before it actually open my steam account. It wasnt that slow before, and I already tried to reinstall both steam and account switcher...

**Desktop (please complete the following information):**
Win10 22H2

**Comment by TCNOco** [comment]
I'm not sure what could be causing this... Nothing has changed with the project in months, sadly, I've been too busy involved in other things... So it's not the project -- 
I'm not entirely sure what it could be, but this is the first issue of this type I've seen.

**Comment by AcTiViSioN911** [comment]
> I'm not sure what could be causing this... Nothing has changed with the project in months, sadly, I've been too busy involved in other things... So it's not the project -- I'm not entirely sure what it could be, but this is the first issue of this type I've seen.

I tried to run switcher as admin, checked "run steam as admin", switched method to close steam to "combined" (its recommended but not set by default?), and method to start steam to "direct"... it takes exactly 15 seconds.
