### ISSUE TITLE
Honkai Star Rail

### ISSUE THREAD

**Issue by LordBeany** [TCNOco/TcNo-Acc-Switcher#316]
I have been trying to setup Honkai Star Rail on the account switcher, but I am having trouble figuring out where the login files are located. I don't know if I only have to worry about files or if I have to look into the registry for the files I am looking for.

**Comment by TCNOco** [comment]
This entirely deepends on how the game works. It could be just the files, just the registry or both. Every game is made in it's own unique way and it just takes some testing to see what works.

I do have this Wiki page about tools I use to help create game/program switchers here: https://github.com/TCNOco/TcNo-Acc-Switcher/wiki/Help-code-a-platform

Lets you easily compare files, folders and registry entries.

**Comment by TCNOco** [comment]
This is coming in the next release!
