### ISSUE TITLE
How to use -vgui shortcut for account switching with TcNo Acc Switcher?

### ISSUE THREAD

**Issue by Void48** [TCNOco/TcNo-Acc-Switcher#318]
The new UI is really bad. Is there any way I can have the program use -vgui for switching accounts? @TCNOco

**Comment by TCNOco** [comment]
Update to the latest TcNo Account Switcher version: https://github.com/TCNOco/TcNo-Acc-Switcher/releases/tag/2023-06-26_00

In the Steam account switcher section you should now see this:

![image](https://github.com/TCNOco/TcNo-Acc-Switcher/assets/10319195/8fb37b55-be96-4d73-84ed-801eb6bebb96)

Let me know if this works for you.
