### ISSUE TITLE
Riot Games Forget account isn't working

### ISSUE THREAD

**Issue by NaniDaFuck** [TCNOco/TcNo-Acc-Switcher#320]
since last update and it it's not working

**Comment by azenia** [comment]
Doesn't work on Battlenet either, starting to think it might not work on any platforms perhaps?

**Comment by NaniDaFuck** [comment]
yea i rolled back to old version!

**Comment by azenia** [comment]
which version you got?

**Comment by TCNOco** [comment]
I have disabled automatic updates to the latest version. You shouldn't get an update message when using the previous version.

This was last known working in https://github.com/TCNOco/TcNo-Acc-Switcher/releases/tag/2023-06-27_01

I will look into fixing this as soon as time allows.

**Comment by fayth78** [comment]
> I have disabled automatic updates to the latest version. You shouldn't get an update message when using the previous version.
> 
> This was last known working in https://github.com/TCNOco/TcNo-Acc-Switcher/releases/tag/2023-06-27_01
> 
> I will look into fixing this as soon as time allows.

Testing that version and it also does not forget strangely. Ill upload any logs in a bit

**Comment by Vojtak42** [comment]
It doesn't work for EA app on old version either (for me).

**Comment by TCNOco** [comment]
Fixed with the [latest release](https://github.com/TCNOco/TcNo-Acc-Switcher/releases/latest) - Ready for download!
Closing this issue as resolved. Thanks for the input.
If there are any issues, let me know on Discord, or through a new issue.
