### ISSUE TITLE
not quiet sure why it never worked on ubisoft connect

### ISSUE THREAD

**Issue by BestSumy** [TCNOco/TcNo-Acc-Switcher#323]
Problem is the account will never stored, confirmed steam is working perfectly

**Comment by BestSumy** [comment]
quick update, both EA Dekstop and Uplay are not working

**Comment by Hiethen** [comment]
This is also happening to me with Ubisoft Connect, I am also unable to "Forget" the account.

**Comment by TCNOco** [comment]
Fixed with the [latest release](https://github.com/TCNOco/TcNo-Acc-Switcher/releases/latest) - Ready for download!
Closing this issue as resolved. Thanks for the input.
If there are any issues, let me know on Discord, or through a new issue.
