### ISSUE TITLE
TcNo accoutn switcher quits game while switching accounts (Overwatch/battlenet)

### ISSUE THREAD

**Issue by azenia** [TCNOco/TcNo-Acc-Switcher#324]
I often switch account back  to another account, but seems like this update broke something.
Whenever swapping accounts with Overwatch open, it would close Overwatch (and as well as logging in right battlenet account), 
rather than the expected outcome being: Leaving Overwatch open/unaffected (and logged in) and changing battlenet account only.

I've tried manually logging out and back in to another account without TcNo account to see if it's the program or just battlenet, but it seems to be the program.

**Comment by TCNOco** [comment]
In `TcNo Account Switcher > BattleNet > Settings` does changing the exit method change anything? 
![image](https://github.com/TCNOco/TcNo-Acc-Switcher/assets/10319195/1cc3981b-ca5d-49c5-a6ab-61470b96bc2d)

I haven't changed the processes that are closed, but I feel the default method changed.
TaskKill should fix this? If so, let me know and I'll make it the new default.

**Comment by azenia** [comment]
Yes, this seems to solve it, putting it on "Close" has no issue with me so far (Combined or taskkill seems to make overwatch close with it), thanks for the help

**Comment by TCNOco** [comment]
I will make this the default with the next update ;)

**Comment by azenia** [comment]
Thank you!
