### ISSUE TITLE
.Net runtime

### ISSUE THREAD

**Issue by Mahmoud0Samy** [TCNOco/TcNo-Acc-Switcher#326]
When I try to open the app I get this message "to run this application you must install missing frameworks for .NET", and when I first said yes a [.NET 6.0 Desktop Runtime (v6.0.19) - Windows x64 Installer](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.19-windows-x64-installer?cid=getdotnetcore) opened and after download and installation nothing happened I still get the same message but when I press yes nothing happens.
I restarted my computer nothing happened
I downloaded TcNo-Acc-Switcher again and i got this message while installation
![image](https://github.com/TCNOco/TcNo-Acc-Switcher/assets/62896510/99c49359-4010-4b2e-87e4-c0aa08b4a72c) 
I installed this [.NET 6.0 Runtime (v6.0.0) - Windows x64 Installer](https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-6.0.0-windows-x64-installer) instead to see if it will work and I still get the message

**Comment by titanic1233** [comment]
same problem

**Comment by TCNOco** [comment]
Try downloading the `ASP.NET Core Runtime 6.0.20 - Hosting Bundle` as well, this should fix the issue:
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-6.0.20-windows-hosting-bundle-installer

**Comment by titanic1233** [comment]
> Try downloading the `ASP.NET Core Runtime 6.0.20 - Hosting Bundle` as well, this should fix the issue: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-6.0.20-windows-hosting-bundle-installer

so i downloaded and installed it. then, it didnt work so i uninstall all .net files using bcuninstaller and installed it working thank you

**Comment by Mahmoud0Samy** [comment]
> 
> 
> 
> > Try downloading the `ASP.NET Core Runtime 6.0.20 - Hosting Bundle` as well, this should fix the issue: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-aspnetcore-6.0.20-windows-hosting-bundle-installer
> 
> so i downloaded and installed it. then, it didnt work so i uninstall all .net files using bcuninstaller and installed it working thank you

Okay i will try it but what is bc uninstaller

**Comment by TCNOco** [comment]
This should be solved with the [latest release](https://github.com/TCNOco/TcNo-Acc-Switcher/releases/latest) - Ready for download!
Closing this issue as resolved. Thanks for the input.
If there are any issues, let me know on Discord, or through a new issue.

This project bumped to .NET 8, and so a lot of issues like this should have been solved and improved by Microsoft as well :)
