### ISSUE TITLE
All Accounts just vanished from the list

### ISSUE THREAD

**Issue by TheSuspect2306** [TCNOco/TcNo-Acc-Switcher#330]
i have all accounts still in steam and they just vanished form the switcher so i need to login to all of them again i even have a old backup but it just says, extracting for hours but does nothing, how to fix it without loggin in again ?

**Comment by TCNOco** [comment]
Are you using [2023-07-05](https://github.com/TCNOco/TcNo-Acc-Switcher/releases/tag/2023-07-05_00), the latest release?

Check the Steam folder for `loginusers.vdf_last` and see if copying and replacing `loginuser.vdf` helps. Default location: `C:\Program Files (x86)\Steam\config`.

Assuming the `vdf_last` or `vdf` file does have text in it you should be able to 'bring the accounts back'. If you do see text in them but are still unable to load them in the account switcher, please send them to me on Discord as it will help development (assuming the files aren't empty). https://discord.gg/MQS4SJpwPt. I am `@troublechute`.

**Comment by TheSuspect2306** [comment]
so the files are empty both, does that mean its all lost ? because i still have a old backup but as i said it doesnt work

**Comment by TheSuspect2306** [comment]
oh wait there is a loginusers.vdf.error and that contains everything

**Comment by TheSuspect2306** [comment]
i found the issue in the vdf, in every account was "SkipOfflineModeWarning" " instead of "SkipOfflineModeWarning" "0", so the " had no exit or something, thanks for the help

**Comment by TheSuspect2306** [comment]
oh yea, if you need this as fixing this issue if i am not the only one, it was caused at least for me because i had a second steam installation open and then opened the switcher and it broke totally

**Comment by TCNOco** [comment]
> i found the issue in the vdf, in every account was "SkipOfflineModeWarning" " instead of "SkipOfflineModeWarning" "0", so the " had no exit or something, thanks for the help

Yep this was an issue with the previous versions... and should be fixed with the latest release. Unfortunately, if this happened the next load cleared the file, causing all accounts to be 'lost'. Very annoying :/

You got this issue using the latest version?

**Comment by TheSuspect2306** [comment]
so i got this issue and then updated, basically i got this issue a version older

**Comment by TCNOco** [comment]
Alright. Should already be fixed, a little annoying that it did happen... Thanks.
