### ISSUE TITLE
A special option must be set for the user

### ISSUE THREAD

**Issue by hamza-al-dulaimi** [TCNOco/TcNo-Acc-Switcher#331]
This option must be included in the settings in the event that I log out of my steam, and when I have logged in via TcNo-Acc-Switcher, I must save the password so as not to be annoying to some people. Retype it again with the username. This option is saved in TcNo-Acc-Switcher too

**Comment by TCNOco** [comment]
`event that I log out of my steam` -> This is intended behaviour.
You should only use the TcNo Account Switcher to change accounts. I'm not sure about the now built-in change account feature of Steam, but I would say the only reliable way to 'stay logged in' is to switch accounts using the TcNo Account Switcher. Logging out on Steam, changing user and more have effects on how Steam remembers accounts being logged in.

The TcNo Account Switcher does not save passwords or login details for Steam. All it does is tell steam what the last logged in user was by changing that bit of text on the filesystem. Steam handles keeping accounts logged in and the rest.

Using `log out` on steam will log you out, stopping you from logging in again by telling Steam 'I was logged in with X before'. You will need to enter a username and password again.

If I've misunderstood this please do reply and reopen the issue.
