### ISSUE TITLE
asks for a password every switch on riot client

### ISSUE THREAD

**Issue by StoqnSS14** [TCNOco/TcNo-Acc-Switcher#332]

**Comment by Allerek** [comment]
Happens to me also. Tried running as admin, checking 'remember me' etc, nothing works at all

**Comment by TCNOco** [comment]
Fixed with the [latest release](https://github.com/TCNOco/TcNo-Acc-Switcher/releases/latest) - Ready for download!
Closing this issue as resolved. Thanks for the input.
If there are any issues, let me know on Discord, or through a new issue.
