### ISSUE TITLE
Loop restart on launch / update

### ISSUE THREAD

**Issue by Vic2077** [TCNOco/TcNo-Acc-Switcher#333]
The app is now restarting infinitely afer trying to update itself.

**To Reproduce**
1. Accept the self-Update prompt.
2. Wait until update is finished.
3. App restarts and goes into a loop.

Screenshot: http://puu.sh/JMW05/63d1b2d114.png

OS: Windows 7 Service Pack 1 (x64)

Not sure since which update this issue has appeared since I wasn't using the app for many months (if not several years), but today it suddenly started itself (maybe I have accidentally clicked its icon on the TaskBar, though), prompted me for a self-update and when I've accepted the prompt it started rebooting until I've closed it after like 10th reboot in a row. Now I get the update/reboot loop every time I try to launch the app.

**Comment by TCNOco** [comment]
Very odd. Simple fix: Download the installer and run it again, or download the .zip/.7z containing the programs files and replace your existing program files.
https://github.com/TCNOco/TcNo-Acc-Switcher/releases

The default install location should be: `C:\Program Files\TcNo Account Switcher`

---
As for fixing the issue, do you know what version you're updating from?

**Comment by Vic2077** [comment]
Not sure.
Well, I've tried replacing the files manually, using TcNo-Acc-Switche_2023-07-05_00.7z

Nothing has changed (I still see that updating loop on app launch attempt).

Should I try to remove the whole folder and do a fresh install?

**Comment by Vic2077** [comment]
UPD: Fresh install changed nothing, but I've got an error message during installation. Something like http://puu.sh/JNzOw/a9ee3ab444.png (this particular screenshot is not mine, because I forgot to take a screenshot - I took it from Google, but the error is similar - something about some "Entry Point" in KERNEL32.DLL. Also my m,essage was in Russian, so I don't know if my screenshot would be of more use to you than this one).

Another re-install didn't show this error message, but the app still loop-restarts on launch, trying to update CEF.

I've also tried to replace all the files with files from TcNo-Acc-Switcher_and_CEF_2023-07-05_00.7z but that also changed nothing.

I guess it's just another app that doesn't work on Windows 7 anymore, because of the recent Google Chorme updates. (I get this Entry Point in Kernel32.dll error for many apps lately. I've been told I need to switch to Windows 10 or 11 for them to work.)

**Comment by TCNOco** [comment]
This is an older issue. I'll close as solved in a more recent update.
Download the [latest release](https://github.com/TCNOco/TcNo-Acc-Switcher/releases/latest) if you haven't already.
If this is still an issue please re-open, comment or let me know via Discord.

I have worked on the updater and the main program quite a bit since this issue. Windows 7 isn't supported by much, and not really by this project either.
