### ISSUE TITLE
New platform request: Honkai StarRail

### ISSUE THREAD

**Issue by YumamaX3** [TCNOco/TcNo-Acc-Switcher#334]
`
"Honkai StarRail": {
      "Identifiers": [ "hsr", "starrail", "honkaistarrail" ],
      "ExeLocationDefault": "%ProgramFiles%\\Star Rail\\Games\\StarRail.exe",
      "ExesToEnd": [ "StarRail.exe" ],
      "PathListToClear": [ "SAME_AS_LOGIN_FILES" ],
      "LoginFiles": {
        "REG:HKCU\\Software\\Cognosphere\\Star Rail:MIHOYOSDK_ADL_PROD_OVERSEA_h1158948810": "UNIQUE_ID"
      },
      "ExitBeforeInteract": true,
      "UniqueIdFile": "HKCU\\SOFTWARE\\Cognosphere\\Star Rail:MIHOYOSDK_ADL_PROD_OVERSEA_h1158948810",
      "UniqueIdMethod": "REGKEY"
    },
`

For Honkai Starrail

**Comment by grenyavolki** [comment]
> `"Honkai StarRail": { "Identifiers": [ "hsr", "starrail", "honkaistarrail" ], "ExeLocationDefault": "%ProgramFiles%\\Star Rail\\Games\\StarRail.exe", "ExesToEnd": [ "StarRail.exe" ], "PathListToClear": [ "SAME_AS_LOGIN_FILES" ], "LoginFiles": { "REG:HKCU\\Software\\Cognosphere\\Star Rail:MIHOYOSDK_ADL_PROD_OVERSEA_h1158948810": "UNIQUE_ID" }, "ExitBeforeInteract": true, "UniqueIdFile": "HKCU\\SOFTWARE\\Cognosphere\\Star Rail:MIHOYOSDK_ADL_PROD_OVERSEA_h1158948810", "UniqueIdMethod": "REGKEY" },`
> 
> For Honkai Starrail

Thanks a lot!

**Comment by TCNOco** [comment]
Added with the latest release - Ready for download!
Closing this issue as resolved. Thanks for the input.
If there are any issues, let me know on Discord, or through a new issue.
