### ISSUE TITLE
All Added Accounts Disappeared

### ISSUE THREAD

**Issue by AkibaRL** [TCNOco/TcNo-Acc-Switcher#335]
**Describe the bug**
Added another account and it made all other accounts disappear

**To Reproduce**
1. Go to 'Epicgames'
2. Click on 'Add New'
3. Add an account (dont give it a name)

**Expected behavior**
All accounts should be gone besides the nameless one you just added

**Screenshots**
(actually 

**Desktop (please complete the following information):**
 - OS: Windows 10

**Additional context**
Adding an account without naming it somehow deletes all the files in the "LoginCache" folder (Epic Games in my case) all thats left is the newly added account (trying to change the name of said account doesnt work and Forgetting it also doesnt do anything it just stays so you gotta delete it manually from the folder

(I think whats happening is that the name you give the account you add is the name of the folder where the account is going to be saved. Not giving it a name results in it just not giving it a folder, deleting all existing accounts to clear the files and then adding the new account. i could be wrong but that is probably what happened)

(To my knowledge its not reversable so i have to add 100+ accounts all over again but it would be good for other to know or for it to be fixed so it doesnt happen to people..)

**Comment by Jokers99** [comment]
me to All Added Accounts Disappeared

**Comment by TCNOco** [comment]
Usernames were never intended to be left empty. Causes a whole bunch of issues. Never thought to test for this. I have added a min length of 1 character. This issue will be fixed with the next release.

**Comment by TCNOco** [comment]
Fixed with the [latest release](https://github.com/TCNOco/TcNo-Acc-Switcher/releases/latest) - Ready for download!
Closing this issue as resolved. Thanks for the input.
If there are any issues, let me know on Discord, or through a new issue.
