### ISSUE TITLE
Can only switch to accounts once

### ISSUE THREAD

**Issue by AkibaRL** [TCNOco/TcNo-Acc-Switcher#336]
Just noticed that i cant switch to any account more than once after i have switched to it once it wont let me select it anymore. i can still rightclick the account but nothing works. "Swap to account", "Change switcher name", "Forget" etc dont do anything they dont work for some reason.

**Comment by TCNOco** [comment]
This is an older issue. I'll close as solved in a more recent update.
Download the [latest release](https://github.com/TCNOco/TcNo-Acc-Switcher/releases/latest) if you haven't already.
If this is still an issue please re-open, comment or let me know via Discord.
