### ISSUE TITLE
we need to add easy login for graphics drivers like GeForce experience 

### ISSUE THREAD

**Issue by mr666devil** [TCNOco/TcNo-Acc-Switcher#337]
the most of the login bugs fixed but we wished to able add more apps that not supported by TcNo Acc Switcher 
![TcNo Account Switcher 9_2_2023 1_07_32 AM](https://github.com/TCNOco/TcNo-Acc-Switcher/assets/103068529/4defc86a-ccd2-4cdb-8ad7-9c3582358356)
it need add for more apps button in this section

**Comment by TCNOco** [comment]
This is much easier said than done. As much as one might think adding is just:
Click `Add programs` > Navigate to program folder > Select EXE > Switch accounts as normal...

The process is far more in-depth. There are multiple files, registry entries and other pointers to which account was "last logged in" that is unique for every program added to this account switcher. The steps for finding these registry entries and/or files and folders is simple but a long task.

See the full process of adding a platform on the [Help code a platform](https://github.com/TCNOco/TcNo-Acc-Switcher/wiki/Help-code-a-platform) section of the Wiki.

To see the full code for each program and game currently supported, you can see the [Platforms.json](https://github.com/TCNOco/TcNo-Acc-Switcher/blob/master/TcNo-Acc-Switcher-Server/Platforms.json) file.
