### ISSUE TITLE
How to not show as Active Game in Discord?

### ISSUE THREAD

**Issue by Buzzker** [TCNOco/TcNo-Acc-Switcher#338]
![image](https://github.com/TCNOco/TcNo-Acc-Switcher/assets/7758237/7f53aad3-600a-4ebf-a9bf-f36b6e397929)
How do i disable this status?

The tool is not shown in Activity Settings - Registered games
![image](https://github.com/TCNOco/TcNo-Acc-Switcher/assets/7758237/0371b3d5-c623-4400-8b4f-24f11ba6262d)

**Comment by TCNOco** [comment]
1. Settings
![image](https://github.com/TCNOco/TcNo-Acc-Switcher/assets/10319195/685efcba-3741-48ea-844b-c89261eee910)

2. Untick Discord at the bottom of the settings window
![image](https://github.com/TCNOco/TcNo-Acc-Switcher/assets/10319195/d4af667a-60df-4ea3-8e80-869d5c8995e0)
