### ISSUE TITLE
[Create shortcut] User name missing

### ISSUE THREAD

**Issue by wonson** [TCNOco/TcNo-Acc-Switcher#339]
When create shortcut to desktop, the created shortcut name is `Switch to (Status) [Steam]`. However, the most important username is not included.

In this case, if I create shortcut for 2 accounts, the 2nd account shortcut cannot be created due to name collision.

Username not included is not user friendly as well

**Expected Behavior:**

Create shortcut with name `Switch to (Status) [Steam] Username`

**Comment by Salamunder** [comment]
My bad 😢
