### ISSUE TITLE
TcNo Switcher doesn't open at all

### ISSUE THREAD

**Issue by AaraenYT** [TCNOco/TcNo-Acc-Switcher#341]
**Describe the bug**
Program doesn't open whatever I try doing (reinstalling, rebooting my computer, ...)

**To Reproduce**
1. Launch Program
2. Program doesn't launch

**Expected behavior**
Program should've opened I think

**Desktop (please complete the following information):**
 - Windows 11 22H2

**Additional context**
Help please

**Comment by TCNOco** [comment]
This should hopefully have been improved with the [latest release](https://github.com/TCNOco/TcNo-Acc-Switcher/releases/latest) - Ready for download!
I'll close this issue as resolved for now, but please do let me know if you're still experiencing issues.
If there are any issues, let me know on Discord, or through a comment on this.
