### ISSUE TITLE
I can't switch between accounts in Steam and it also asks me to enter my password and my email 

### ISSUE THREAD

**Issue by gg5500** [TCNOco/TcNo-Acc-Switcher#344]
I can't switch between accounts in Steam and it also asks me to enter my password and my email What should I do @TCNOco ?

**Comment by gg5500** [comment]
What should I do? @TCNOco

**Comment by gg5500** [comment]
When I switch accounts using tcno, it does not switch the account and also asks me to enter the password and email.

**Comment by TCNOco** [comment]
Please try the [latest release](https://github.com/TCNOco/TcNo-Acc-Switcher/releases/latest) - and let me know if this has improved.
