### ISSUE TITLE
new update

### ISSUE THREAD

**Issue by saintlucifer1075** [TCNOco/TcNo-Acc-Switcher#346]
hi TCNO as u said in ur recent video there is a brand new account switcher for steam that is its own official account switcher but it only support up to 5 accounts and for some reasons i have more than 15 accounts that i have to switch between and ur account switcher just bring up the steam switcher so is there any way that you could help me by updating your lovely switcher to work instead of steam's switcher?

**Comment by 0rk** [comment]
@TCNOco hi, this problem is also being reproduced for me, can you tell me if you know about it?
