### ISSUE TITLE
Rockstar Launcher Account Problems

### ISSUE THREAD

**Issue by Insomniac05** [TCNOco/TcNo-Acc-Switcher#347]
So I have a few different accs for Social Club as I have GTA V on 3 platforms
The thing is that only 1 account created the settings_user.dat file the other accs don't seem to create it at all so the program can't save these accs
If possible kindly fix this

The account that made the file was one  which owns gta v on rockstar launcher the other accs own the game on epic and steam

**Comment by TCNOco** [comment]
Fixed with the [latest release](https://github.com/TCNOco/TcNo-Acc-Switcher/releases/latest) - Ready for download!
Closing this issue as resolved. Thanks for the input.
If there are any issues, let me know on Discord, or through a new issue.
