### ISSUE TITLE
(Epic Games) asks for a password every switch

### ISSUE THREAD

**Issue by TheCrafter8000** [TCNOco/TcNo-Acc-Switcher#348]
I haven't touched anything. This was working just a month ago and now all of the sudden, every other account is asking me to login again.

**Comment by Salamunder** [comment]
I just tried it with two accounts and was not prompted to login. Maybe you did not sign in recently so the auth expired?

**Comment by NoPlagiarism** [comment]
Seems to be EG problem: https://www.reddit.com/r/EpicGamesPC/comments/it97cj/epic_games_logs_you_out_sooner_than_30_days/

**Comment by TCNOco** [comment]
Yikes a 30-day limit to sessions is sad... But at least when you do log in again and switch after it should save the latest token anyway, refreshed for another 30 days.
