### ISSUE TITLE
Status of this project

### ISSUE THREAD

**Issue by w1nsid** [TCNOco/TcNo-Acc-Switcher#353]
Will there be an update to account switcher, are there any alternatives that work for steam ?

**Comment by TCNOco** [comment]
Updates, yes. Timeline, no. This is a passion project and has been something I had tons of time to sink into. Now I have many more responsibilities and need to prioritize tasks that pay the bills... So this project has fallen behind.

I have lots of plans for lots of projects, but struggle to meet them, especially with almost no-income passion projects. There have been so many issues on Microsoft's side for WebView, such as the inability to drag and drop with it... Speaks for itself.

The next steps are small updates, and hopefully a full rewrite in something more competent than Microsoft WebView2.

The TcNo Account Switcher still works for Steam and many other platforms, nothing's changed for a lot of them.

**Comment by w1nsid** [comment]
Thank you for the reply and good luck in your endeavors.
