### ISSUE TITLE
Adding/switching discord accounts does NOT work

### ISSUE THREAD

**Issue by vvirtues** [TCNOco/TcNo-Acc-Switcher#361]
**Describe the bug**
using the switcher for discord does not save the account or load it, the only thing it does is closing discord

**To Reproduce**
1. Open TcNo Acc switcher
2. Click on `discord`
3. click `save current`
4. See error (also consistently says `copying user files` but it actually stopped)

**Expected behavior**
Save my discord account since ion like discord's built in one

**Screenshots**
![image](https://github.com/TCNOco/TcNo-Acc-Switcher/assets/81705406/af36443f-d500-47ca-b26d-97ad8caeef65)

**Desktop (please complete the following information):**
 - OS: Win 11 23h2

**Comment by CyberEnemy** [comment]
I get the same error, doing the same prompt. 
I even tried to create said 'Cookies' folder in that Discord directory, but as soon as I open Discord, the 'Cookies' folder gets deleted instantly.

**Comment by dragonGRaf** [comment]
same here with win 10
but ig that was already w^known

**Comment by EgySamoha** [comment]
same

**Comment by C4J3** [comment]
As of a couple of years ago Discord started developing their own in-built account switcher. This allows you to also switch between accounts without relogging so I imagine they have changed how they store data for user accounts on client systems for both users with and without this feature rolled out to. Folders like %appdata%/discord/Cookies no longer exist (At least I don't have one on my machine) so I presume TCNOco's Discord switching implementation no longer functions. 

You can read more about the in-built one [here](https://support.discord.com/hc/en-us/articles/4412732047127-Discord-Account-Switcher-FAQ).

**Comment by vvirtues** [comment]
> As of a couple of years ago Discord started developing their own in-built account switcher. This allows you to also switch between accounts without relogging so I imagine they have changed how they store data for user accounts on client systems for both users with and without this feature rolled out to. Folders like %appdata%/discord/Cookies no longer exist (At least I don't have one on my machine) so I presume TCNOco's Discord switching implementation no longer functions.
> 
> You can read more about the in-built one [here](https://support.discord.com/hc/en-us/articles/4412732047127-Discord-Account-Switcher-FAQ).

yea but [they might limit/ban your alts if u break the rules](https://support.discord.com/hc/en-us/articles/4412732047127-Discord-Account-Switcher-FAQ)

I prefer a 3rd party one so that discord doesnt know about my alts

**Comment by TCNOco** [comment]
This is fixed in the upcoming version. Releasing soon! https://github.com/TCNOco/TcNo-Acc-Switcher/commit/c2ac0ec8638da27113c972aad70a9fd7ff3049cb

**Comment by TCNOco** [comment]
Fixed with the [latest release](https://github.com/TCNOco/TcNo-Acc-Switcher/releases/latest) - Ready for download!
Closing this issue as resolved. Thanks for the input.
If there are any issues, let me know on Discord, or through a new issue.
