### ISSUE TITLE
EA APP is not available 

### ISSUE THREAD

**Issue by touhamii** [TCNOco/TcNo-Acc-Switcher#362]
hi , thank u for this awesome project
any idea when is EA going to be available ? 
i tried origin with EA  but not working

**Comment by Wontell** [comment]
> hi , thank u for this awesome project any idea when is EA going to be available ? i tried origin with EA but not working

OP, its there and im using it, click on the "+Manage Platforms" button and add EA Desktop.
Origins is unnecessary since EA no longer supports it

**Comment by touhamii** [comment]
i didn't see it for some reason , thank you so much
