### ISSUE TITLE
Failed to load XML of <Steam ID>. Program will remain frozen until reload

### ISSUE THREAD

**Issue by Adzeiros** [TCNOco/TcNo-Acc-Switcher#368]
**Describe the bug**
Downloaded the program and kept getting the "Program needs to update" message regardless of how many times I updated it. I ignored it and go into the steam tab, immediately errors flood in stating it cant load the XML of any of my steam accounts. Keep in mind that my firewall blocked outbound data from the application marking it as suspicious. I find it odd that the application is trying to send data somewhere when it claims it doesn't.

**To Reproduce**
1. Go to Steam module
2. See error

**Expected behavior**
For it to load the accounts and display them, giving the option to swap between them.

**Screenshots**
https://i.imgur.com/IM13Anw.png

**Desktop (please complete the following information):**
 - OS: Windows 11

**Comment by rajlyanu** [comment]
It's been working fine for me so far, but today I just started getting errors like this

**Comment by TCNOco** [comment]
Closing as this is an older issue.
The XML details it mentions are your Steam profile image from Steam by requesting it with your saved Steamid for each account. Just your usual steam profile page, plus XML at the end to receive an app-frindly version of your profile. Nothing suspicious, or nowhere it "claims it doesn't". This application is completely open source should you not trust it you are free to browse the entire source code.

It should work fine without the internet. The errors shown in app are letting you know Steam's website was unreachable, and show as the error should be handled (as in stepped over without a crash).
