### ISSUE TITLE
Unable to save Riot account

### ISSUE THREAD

**Issue by valampz** [TCNOco/TcNo-Acc-Switcher#369]
**Directory not found**
Can't save riot account (Valorant).

**To Reproduce**
1. Go to 'RIOT GAMES'
2. Click on 'ADD NEW'
3. Login with the credentials
4.Click on 'Save Current'
5. See error

**Expected behavior**
Show 'Success' pop-up and save the account. But instead I get this:

Directory not found
Could not find
C:\Users\tazim\AppData\Local\Riot Games\Riot Client\Data\Cookies\

(I also manually checked the directory myself, for some reason there's no 'Cookies' folder)

**Screenshot**
![Screenshot 2024-03-20 025124](https://github.com/TCNOco/TcNo-Acc-Switcher/assets/59084210/08f68cef-7f6f-4c15-9dd2-9d8152d948d0)

**Desktop:**
 - OS: Win 11 22H2 Build 22621.3296

**Additional context**
New icon gets saved but clicking on them leads to the login part. Forget' option isn't working, I have to manually delete the folders from the cache folder to remove those account icons.

EDIT: Manually creating the 'Cookies' folder fixed the issue

**Comment by NaniDaFuck** [comment]
can u tell me how to save riot accounts cause it doesn't work for me

**Comment by NaniDaFuck** [comment]
Valorant to be specific  when i saved league account it worked but valorant didn't !

**Comment by NaniDaFuck** [comment]
followed steps from https://youtu.be/cee0IFr7gqk

**Comment by NaniDaFuck** [comment]
alright it's working but i guess we just have to restart pc 
it's not working exactly right after saving it

**Comment by Euro-pol** [comment]
also get that error

**Comment by Zephyr7735** [comment]
Hi,
i cannot save my riot accoutant in my TcNo

Could you pls to help me for fixing this issue

**Comment by Zephyr7735** [comment]
According to my asked, you've'nt already answered.

Could you pls to help me to figure out this issue 

Moreover, it possible to delete some switch because i loaded many switch and i want to delet some on 



Thx in advance,
De Macedo Marwan

**Comment by Tazim141** [comment]
IG this project is abandoned, try [this](https://github.com/HeyM1ke/Assist) instead.

**Comment by Zephyr7735** [comment]
I asked about Riot games not valorant

**Comment by TaniKyuun** [comment]
Work around for this issue is creating a folder called "Cookies" at "C:\Users\[Username]\AppData\Local\Riot Games\Riot Client\Data\"

![image](https://github.com/TCNOco/TcNo-Acc-Switcher/assets/72883511/6de13dd2-e6d7-4375-8e73-0563b6618831)

Make sure you clean the LoginCache for Riot Client at TcNo AppData folder and try again if you encounter the issue
"C:\Users\[Username]\AppData\Roaming\TcNo Account Switcher\LoginCache\Riot Games"

**Comment by TCNOco** [comment]
Fixed with the [latest release](https://github.com/TCNOco/TcNo-Acc-Switcher/releases/latest) - Ready for download!
Closing this issue as resolved. Thanks for the input.
If there are any issues, let me know on Discord, or through a new issue.
