### ISSUE TITLE
Why does my PC load so much?

### ISSUE THREAD

**Issue by rajlyanu** [TCNOco/TcNo-Acc-Switcher#373]
When this program is turned on, the computer loads heavily.
The fan is running at full power.
Probably some hidden miner is turning on?

**Comment by TCNOco** [comment]
There is no miner. This software is completely open source and if you choose not to trust it you are able to build a working version by downloading the source code at any time.

This program is similar to Discord in that it runs a WebView (Essentially a Chrome browser) with everything displayed in it. If there is something with your configuration causing an infinite loading loop, or something similar, then clearing your settings and cache for it may help.

Settings and cache for the program are found in `%AppData%\TcNo Account Switcher\`.
