### ISSUE TITLE
WebView crashes after updating Nvdia drivers

### ISSUE THREAD

**Issue by eiddor** [TCNOco/TcNo-Acc-Switcher#378]
**Describe the bug**
When I update my Nvidia drivers, the app crashes.  This has been happening since I started using the app over a year ago, and it's not a big deal (I just relaunch), but I figured I'd report it just for tracking purposes.  It's happening on two different PCs as well (one desktop, one laptop; both Nvidia.)

**To Reproduce**
1. Update Nvidia Drivers through GeForce Experience
2. TcNo-Acc-Switcher crashes with:

> "The WebView browser process has crashed! The program will now exit."

**Expected behavior**
I expect it not to crash :-)

**Screenshots**
![image](https://github.com/TCNOco/TcNo-Acc-Switcher/assets/7586731/37ff4a9b-9217-4330-bcf4-3b48e47baec9)

**Desktop (please complete the following information):**
 - OS: Windows 11 Pro (Build 22631) on both PCs

**Comment by TCNOco** [comment]
I assume if the program is running WHILE your driver is updating a crash is expected.
If this crash is happening AFTER updating, and restarting the TcNo Account Switcher then please let me know by replying and I will re-open this issue.

After all, WebView is managed by Microsoft themselves. If there is something wrong with it, it will likely be something Microsoft needs to look into. If there's anything I can do to fix it, I will try :)

**Comment by eiddor** [comment]
Ahhh that makes absolute sense - It's definitely during the "while" phase.  I'm not sure if I run any other WebView apps and Account Switcher is always running, so it makes sense why I haven't seen it in other apps.  Thanks for the reply!

**Comment by TCNOco** [comment]
Discord and related apps are Electron, and run a much bigger version of Chrome.
This app uses Microsoft's WebView, which is also technically Chrome, but should be lighter-weight for both download and running. I assume some cases like this may have been overlooked while Microsoft edited it to their means.
Thanks for the quick reply. Sorry for my delayed one!

**Comment by eiddor** [comment]
No worries!  I'm not an app guy, so appreciate the explanation.  I may try to find another WebView-based app to test and close the loop in my mind, but I'm pretty sure you're right.


Also, thank you for an excellent tool!  I use it daily and I'm not even a gamer.

**Comment by TCNOco** [comment]
I have updated CEF with the latest release as it was... more than a few versions behind. It may function as hoped now, who knows :)

What do you use the account switcher for if you're not a gamer?
I added the "OBS Switcher" to swap out ProgramData folders for different settings over the entire application, etc, but haven't used it as of now.

**Comment by eiddor** [comment]
Goofy use-case: I only play Rocket League (and MSFS if we count that as a game), and not even that much, but I switch between accounts often depending on who I'm playing with, so Acc-Switcher was a lifesaver even if I only use it for one game.

Congrats on the new release!
