### ISSUE TITLE
Ubisoft Switching not working

### ISSUE THREAD

**Issue by MajorGamer11st** [TCNOco/TcNo-Acc-Switcher#380]
every time I use ubisoft account switching it does not change to the other account when i logout it doesn't return to the saved account

**Comment by TCNOco** [comment]
Fixed with the [latest release](https://github.com/TCNOco/TcNo-Acc-Switcher/releases/latest) - Ready for download!
Closing this issue as resolved. Thanks for the input.
If there are any issues, let me know on Discord, or through a new issue.
