### ISSUE TITLE
Update directly lead to Vanguard 1067 error

### ISSUE THREAD

**Issue by sodku** [TCNOco/TcNo-Acc-Switcher#390]
Today I was shown, that an update is available. With `v5.0 - 2024-08-25_00` I get:
- **Vanguard 1067 error**

Failed attempts to resolve the issue:
- Tried to restarted the computer multiple times
- uninstalled Windows Remote Desktop (as suggested online)
- reinstalled Vanguard

Workaround (error is gone):
- Uninstall TcoSwitcher

I then tried to install the old version `v5.0 - 2023-07-05_00`
- I get the error 1067 again
- but this time even uninstalling TcoSwitcher does not help, so don't do this!

Thanks for this nice peace of software <3

**Comment by TCNOco** [comment]
Hi.
If you download the portable .zip from https://github.com/TCNOco/TcNo-Acc-Switcher/releases/tag/2023-06-27_01, and run the `TcNo-Acc-Switcher.exe`, do you still get this error? This was the last version.

The Riot switcher was adjusted to properly allow switching of accounts. They store the currently logged in user in a folder called "Sessions" instead of "Cookies" now. Assuming the older version works (where account switching should be broken for Riot Games) this may be the cause.

I have added this path back to the settings file for the next version I'm releasing in a few minutes, and it should be fixed, as this Cookies folder will be used as well if it exists.

**Comment by TCNOco** [comment]
Ignore this @NeonRST by the way. GitHub is being plagued by these malware bots.

**Comment by sodku** [comment]
Unfortunatelly, I fked up my setup yesterday:

As this occurred directly after the TcoSwitcher update I was sure it's the cause.
After uninstalling both, Vanguard and TcoSwitcher and reinstalling Vanguard it was resolved.

But after I installed the `v5.0 - 2023-07-05_00` version again, I get the error and since then are unable to fix it, even after:
- uninstalling and deleting all TcoSwitcher files from my PC
- uninstalling Porofessor (only other app I have on my PC next to League, TcoSwitcher, Vanguard, I only use this OS for League)
- reinstall League of Legends client
- reinstalling Vanguard

Nothing helps. I give up and will reinstall my OS this evening after work.
I'll then try to install the lastest version from 2024-08-25 again to see if this was really the cause
or maybe the actual cause is my SSD as I also get the `chkdsk` promt on each OS boot.
(even though SSD health info software say the health is good: 91%)
Maybe I try multiple SSD this evening just in case.

Cheers for the reply, unfortunatelly, I was too fast trying different things.
But if others have the same issue, please report back here, so we know for sure if this is a local issue or with this TcoSwitcher new version.

**Comment by TCNOco** [comment]
So the older version is also giving you the issue? I'll see if I can recreate this.
The only thing I can think of is:
- The account switcher copies files that say what account is logged in
- When Add New is clicked, those files are deleted.
- When Vanguard tries to start, with those files missing it errors. Reinstalling Vanguard fixes this.
- Solution: Some files need to be left behind when switching accounts

In `%AppData%\TcNo Account Switcher\LoginCache` you should find a Riot Games folder, with your accounts in it. In each folder are the files required to switch to that account. You can always copy them back manually, as all the account switcher does it automatically move files.

The locations are as follows: https://github.com/TCNOco/TcNo-Acc-Switcher/blob/78f2773afe13f6f5a081640db14eb92b4c7b25a2/TcNo-Acc-Switcher-Server/Platforms.json#L219-L225

For example you can copy `Cookies` and/or `Sessions` back to `%LocalAppData%\Riot Games\Riot Client\Data\` as well as each of those other files to their locations and things should work :)
so copy `RiotClientPrivateSettings.yaml` into `%LocalAppData%\Riot Games\Riot Client\Data\`
`RiotClientSettings.yaml` into `%LocalAppData%\Riot Games\Riot Client\Config\`

**Comment by sodku** [comment]
Unfortunately, I've already deleted all TcoSwitcher releated files yesterday night ^^

I'll report back if I can reproduce this issue myself on a clean, new system with another SSD.

**Comment by sodku** [comment]
Just reporting back: On the fresh Windows 11 on a fresh SSD, I can run the latest version (2024-08-25) without issues with Vanguard. I guess it really was the faulty SSD.

Sorry for the inconvenience, you can safely `git revert` the last commit I think.

**Comment by TCNOco** [comment]
Thanks for the update. Odd that something like that happened...
