### ISSUE TITLE
[SUGGESTION] Support different skins for each account

### ISSUE THREAD

**Issue by r6d2** [TCNOco/TcNo-Acc-Switcher#4]
It would be nice, IMHO, to have Steam running on a different skin for each account. I mean simple skins, nothing too fancy, like the ones available in [SteamCustomizer](https://community.steamcustomizer.com/explore).

I don't even know if that's possible, but you might want to have a look.

And thanks a lot for your tool, pretty useful so far. Cheers!

**Comment by TcNobo** [comment]
I'll keep this in mind, though I haven't looked into skinning that deep, and I'm not too familiar with what files it changes.
For now, I'm working on moving from .NET Core to .NET Framework 4.8, as well as working on an Origin account switcher. I'll keep this in mind though :)

**Comment by TcNobo** [comment]
Considered solved :)

**Comment by Tharki-God** [comment]
okay you can add custom skins as an option, the registry keys used by it  are: "HKEY_CURRENT_USER\SOFTWARE\Valve\Steam:Skins" and "HKEY_CURRENT_USER\SOFTWARE\Valve\Steam:SkinsV5"
change these with account and get the result of different skins with a different accounts.

**Comment by TcNobo** [comment]
I'm currently using [Dracula](https://draculatheme.com/steam) for Steam. I know of [Steam Customiser](https://steamcustomizer.com/) - [GitHub](https://github.com/SteamCustomizer/Manager), which is ancient at this point with the last update 5 years ago.

Where do you get skins compatible with the new Steam UI?

**Comment by Tharki-God** [comment]
http://steamskins.org/

**Comment by Tharki-God** [comment]
use metro, its the skin i use, its so damn clean

**Comment by NoPlagiarism** [comment]
Steam updated UI, so... Themes not supported by Steam.

I only know [DeckThemes](https://deckthemes.com) with their [CSSLoader](github.com/beebls/CSSLoader-Desktop)

So.. In CSSLoader there are profiles feature, maybe you can use this

**Comment by TCNOco** [comment]
Yeah I never got around to adding this, and Steam's UI has had some massive changes. I miss the customizability, and assume there will be more in the future, however there should be separate projects that control all those files (I assume many changes of Steam's files will need to be made). If there is a command-line tool that can be used to change themes, or something similar I could implement that here, however I'll mark this as closed for now.

If there is something like `Kevin's Theme Changer.exe --theme Catppuccin`, please let me know in a new issue :)
