### ISSUE TITLE
Ubisoft offline account switcher

### ISSUE THREAD

**Issue by saik2536** [TCNOco/TcNo-Acc-Switcher#400]
Hello sir ,

 Im new to Tcno , can you please clarify my query .

Can Tcno be used to save multiple Ubisoft offline  activated third party accounts with respective games in it  WITHOUT asking for passwords and 2fa code  after account switch  , will that break game activation ?

Hope you understand my query , Im trying to backup multiple  third party  offline activated Ubisoft connect game accounts so i can access games in all those accounts offline using account switcher without having to logout and login

Thanks

**Comment by TCNOco** [comment]
Yes this app allows switching between accounts skipping 2FA/Password as the account i never logged out of - the files that store the accounts state on your machine are moved back and forth depending on which account you're using.

These files won't work on other systems, most likely, and often programs have a period of 30-days (if at all) where accounts will stay valid, until another log-in is required. This happens even if you never used the account switcher - some just require this once in a while.

Game activation, anti-cheats, or anything else isn't messed with. This isn't a cracking tool and can't be used as one by nature.

You can see which files are moved around for the Ubisoft account switcher here: https://github.com/TCNOco/TcNo-Acc-Switcher/blob/27e71c96b3b241f2173866604c9024302358ab12/TcNo-Acc-Switcher-Server/Platforms.json#L317-L345 -- heck you could even be the account switcher, closing, moving those files out, and starting it again to add a new account - for example.

**Comment by saik2536** [comment]
Thanks for your reply , can you please point out above which files are moved to switch accounts , 

Is it the one below "LoginFiles" ?   Does the cache folder need to be moved if doing manually ?

**Comment by saik2536** [comment]
One last thing sir , 
recent Ubisoft connect builds are always forcing online ,  one have to manually force offline in settings.yaml and set it read only to stick else it reverts back to online .
Does Tecno take this change into account ?

**Comment by TCNOco** [comment]
No it doesn't have anything special for Read Only files just yet. I'm not sure how it will handle them. I will look into this behaviour.

**Comment by saik2536** [comment]
well i tried this but unfortunately the game activation breaks.......are you sure only this four files stores all account info including passwords 2fa code need to be moved

**Comment by TCNOco** [comment]
I'll double check with a fresh install of Ubisoft Connect but it seems to be working fine for me :)

**Comment by TCNOco** [comment]
Just tested with a fresh install of everything, works fine out of the box.
Switching accounts and playing games on either of my accounts works fine.

What do you mean by the "game activation breaks"? Do you own the game you're trying to play on _both_ accounts?

Assuming you do own the game you're having issues with on _both_ your accounts, try replacing `Platforms.json` in your TcNo Account Switcher install folder with the following one and see if it helps. I've added more files that aren't exactly required to be switched as well, but are created when logging into an account.
[Platforms.json](https://github.com/user-attachments/files/16851148/Platforms.json)

**Comment by saik2536** [comment]
note Im talking about offline accounts , what i mean by 'game activation breaks' is game is no longer playable offline and have to go online to reactivate , its the Denuvo drm thing......these are third party accounts and I do not have permission to go online multiple times hence my endeavor to save and switch their offline state as needed

**Comment by TCNOco** [comment]
Ah, right, you're signing into the game with another account? Which games are these that you experience this in so I can test and add more things to save between accounts.
Or is this just in general with DRM?
