### ISSUE TITLE
Battle.net max account number

### ISSUE THREAD

**Issue by jorgelpjr** [TCNOco/TcNo-Acc-Switcher#96]
Hello, i writing cuz i try everything to be able to add more than 4 acccounts, but i cant, so idk what to do anymore.

**Comment by TcNobo** [comment]
![2Q2W1uy2HH](https://user-images.githubusercontent.com/10319195/142764811-c341a5d7-4b9c-4018-84ef-dad4d84fc5a1.png)

Unfortunately, I am not able to replicate this. I signed in with 5 different accounts, and I'm able to switch without issue.
These 5 accounts remain on the list after the program and computer restarts.
I am on version 2021-11-20_00 (Yesterday's update).
Do update and let me know if the problem persists.

**Comment by TcNobo** [comment]
Closing as an inactive issue. Comment on this thread to reopen it. I haven't been able to pinpoint the solution, or issue for that matter.
Very few users are having issues with account limits, and Riot is the only one that I know seems to enforce some limit per-computer.

**Comment by aquilonem** [comment]
I have the same problem as described above. It only saves 4 accounts, anything that I can do to help you fix it?

**Comment by TcNobo** [comment]
I'll reopen this for now. I've found the solution and improved it...
However, I've made massive changes to the backend of the program that aren't yet complete.
When the next update comes out, it will be a pretty early "alpha" -- lots of bugs to fix, and it's not even complete yet.
I've definitely done a lot overhauling everything here, and now even onto my site for even more backend...

A timeline? Hopefully sometime before the end of the month.

**Comment by aquilonem** [comment]
So do I have to do anything? :)

**Comment by TcNobo** [comment]
Not yet

**Comment by gabriel-gfs** [comment]
I also have this issue. Looking forward to a fix ❤️

**Comment by TCNOco** [comment]
This should have been solved, I remember working on this.
Please try the [latest release](https://github.com/TCNOco/TcNo-Acc-Switcher/releases/latest) - Ready for download!
Closing this issue as resolved. Thanks for the input.
If there are any issues, let me know on Discord, or through a new issue.
